language: node_js
node_js:
  - "0.11"

# whitelist
branches:
  only:
    - feature/testrunner

install:
    - sudo npm install -g grunt-cli
    - sudo npm install -g bower
    - npm install
    - bower install

before_script:
    - bower install

notifications:
  email:
    on_success: never