language: node_js
node_js:
  - "0.11"

# whitelist
branches:
  only:
    - master

install:
    - gem install jekyll
    - npm install -g grunt-cli
    - npm install -g bower
    - npm install

before_script:
    - bower install

notifications:
  email:
    on_success: never