language: node_js

node_js:
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"

# whitelist
branches:
  only:
    - feature/testrunner

before_script:
  - sudo npm install -g grunt

script: grunt karma:continuous