language: node_js
node_js:
  - "0.11"

# whitelist
branches:
  only:
    - feature/testrunner

before_install: npm install -g grunt-cli
install: npm install

notifications:
  email:
    on_success: never
